# Generated by Django 5.1.6 on 2025-03-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='security_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='student_security_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='teacher_security_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
